language: node_js
node_js:
  - stable
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.yarn-cache
    - $HOME/.node-cache
branches:
  only:
    - master
    - working
    - recover

before_script:
  - npm i -g yarn
  - yarn add -g gulp-cli

install:
  - yarn add -D jest-puppeteer jshint eslint eslint-config-airbnb-base eslint-plugin-import eslint-plugin-import eslint-plugin-jest eslint-plugin-jsx-a11y eslint-config-airbnb
  - yarn add puppeteer
  - yarn add -g codecov jest
  - yarn
script:
  - yarn test
  - codecov
deploy:
  provider: heroku
  api_key:
    secure: TgE0gTwTFCxS512m6KierwRhgPDBP6dNgEFgf/No9fmUcplneFnasaHjh9YEkVUJUWuZEvoicbZdPXVcHOKEKvb9vzT4CacjaJoaJ2fGNxDTCTJqQjtSYgWr+mFhfc2p7Rds0emlevv7qI4DGzHip4y31YFeOuS9eiPvGZiReTDwzgu9VQ7TVaxz50J/wPzseSZjzX6CyTqTYqGtNqrE0hFZj0hzLy70ogmXg+VOIlsnzbX/SfDdWBNM+LJEn9YjYfDBhjftuOlETLmkBPod9zMbQZ8h0aT+pell4cmClOKFm8Rb+/GMMdQ2zcC71LD44X8bdXwMAUnYD9lkuKwDgwJTeuj3ski6esz8KKYA7+HMCWBAzHgKByy+/SsGR7dghffA5kKJp422MfXzXkkDI5/PAI3WFdkBegIvgnK8crYz5mic9lMNgDzBJ857+LxBq03DPOFCVcGiFTggEvGaWA42uWDe2atNOtZqnrg8EioeSDLeHD134TViQkTzhUxf9rWxYC2FN2kdZn+T3Vb5EvChj9wmhv9XJ+KtkA4Pozmce+y3DHl5RvzQOCvhriI8Zvs4Zz08ko05FZMNs49z7q3tWcfBp4buZxf3bk/6Mvmp8ht8p0pYqWKyzirJ/u0BNRoAshf+Q1ICB/dnIWR6ryEIR5PF1uS8UGdG6iZyehs=
  app: covid-tracker-sa
  on:
    repo: TumoM/Covid-Live-Tracker-SA
# jobs:
#   include:
#     - stage: "Style Tests"
#       name: "Hinting Tests"
#       script: yarn hint
#       name: "Linting Tests"
#       script: yarn lint
#     - stage: "Intergration Tests"
#       name: "Unit Tests"
#       script: yarn test
#       name: "Integration Tests"
#       script: yarn test:e2e
#     - stage: "Build"
#       name: " Build Phase"
#       script: yarn build
jobs:
  include:
    - stage: "Style Tests"                # naming the Tests stage
      name: "Hinting Tests"            # names the first Tests stage job
      script: yarn hint
    - script: yarn lint
      name: "Linting Tests"     # names the second Tests stage job
    - stage: "Integration Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: yarn test
    - script: yarn test:e2e
      name: "Integration Test"     # names the second Tests stage job
    - stage: "Build"
      name: "Build Phase"
      script: yarn build
